### ISSUE TITLE
Prebid with GDPR / TCF API v2

### ISSUE THREAD

**Issue by EskelCz** [id5io/id5-api.js#11]
I'm having an issue with getting id5 working with GDPR.

In network I can see my test page sending this:
`https://id5-sync.com/g/v1/250.json?1puid=ID5-ZHMOE2Mtxa95iEFlTy9WMsL-67uNoQCfRZZ6ZwCYSA&gdpr=0&gdpr_consent=`

Although I have the latest consentModule and id5 adapter in latest version of prebid.js. The SSPs are receiving TCFv2 consent string properly, both versions of iab API are available. I'm following this implementation guide: https://console.id5.io/docs/public/prebid
(the GDPR example at the bottom, it's missing an anchor)

So I guess I have two questions:
1. Is TCF api v2 supported by id5?
2. Is there an easy way to debug the adapter?

In prebid logs I can see this order of events:
```
Prebid INFO: User ID - usersync config updated for 2 submodules
Prebid INFO: Invoking pbjs.enableAnalytics for:  [{…}]
Prebid INFO: consentManagement config did not specify allowAuctionWithoutConsent.  Using system default setting (true).
Prebid INFO: consentManagement module has been activated...
```

**Comment by smenzer** [comment]
Hi @EskelCz based on your description you're trying to use the ID5 ID Module within Prebid.js, right? I'd be happy to help you investigate this, but we should either move this issue to the Prebid project or we can take it into email (you can email me at support@id5.io), as this project is for our JS API which is separate from Prebid.js.

If you have a test page that you can share via email/Prebid.js Issue, that would be a great starting point for me to dig in for you.

Thanks!

**Comment by EskelCz** [comment]
@smenzer Hi, you're correct, thanks. I'll e-mail you then.
