### ISSUE TITLE
Debug logs always enabled

### ISSUE THREAD

**Issue by SolanaFish** [id5io/id5-api.js#4]
Hi,
I found an error in code that is responsible for enabling "INFO" logs in browsers console.

In line https://github.com/id5io/id5-api.js/blob/7a5a9e3ad45a7255b5355d3eef070d6887f01d26/src/utils.js#L84
the function config.getConfig is used with parameter, but the function doesn't take parameters and always returns config object, so this line always evaluates to true, thus enabling logs. 

This is undesirable because logs will be active in production environments.

**Comment by padurgeat** [comment]
Thanks for your help !
